title: Tharma Thavaratnam # your name (or website title) here
logo: "/profile.jfif?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Frontend Engineer
  <br><br>
  <a href="mailto:tharma.thavaratnam1@gmail.com">tharma.thavaratnam1@gmail.com</a>
  <br>
  <a href="https://www.linkedin.com/in/tharma-thavaratnam/">LinkedIn Profile</a>
  <br>
  <a href="https://www.gihub.com/tharma-thavam/">Gihub</a> 
theme: jekyll-theme-minimal
